{% set name = "napari-omaas" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: f2541caaba3f6c02577a5034cdbdda8caf6d3b98d8858f93c8c4dc9575f6fa45
  patches:
    - qtpy.patch

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - setuptools
    - pip
    - python {{ python_min }}
  run:
    - magicgui
    - matplotlib-base   # Imported but not listed as requirement
    - napari
    - napari-macrokit
    - napari-mat-file-reader
    - napari-matplotlib
    - napari-sif-reader
    - numpy
    - pandas  # Imported but not listed as requirement
    - pyqtgraph
    - python >={{ python_min }}
    - qtpy
    - requests  # Imported but not listed as requirement
    - scikit-image  # Imported but not listed as requirement
    - scipy  # Imported but not listed as requirement
    - sif-parser

test:
  imports:
    - napari_omaas
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - pyqt
    - python {{ python_min }}

about:
  home: https://pypi.org/project/napari-omaas
  summary: napari-OMAAS stands for Optical Mapping Acquisition and Analysis Software
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/rjlopez2/napari-omaas

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
    - rjlopez2
